services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-net

  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - ./mongo/init.sh:/init.sh
    #      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh
    command: >
      sh -c "
      chmod +rwx /init.sh &&
      bash /init.sh & 
      mongod --replSet rs0 --bind_ip_all
      "
    networks:
      - mongo-net
    depends_on:
      - mongo2
      - mongo3


  mongo2:
    image: mongo
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - mongo-net


  mongo3:
    image: mongo
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - mongo-net


volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  mongo-net:
    driver: bridge